# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - arraymorph

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          cd ./test
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          cd test
          zip -r ../release.zip ./*  
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0BE426576B284B67A4D25848A7C18AB6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E563AE6032A458DAB60E959740FBB0F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F88B946F08B74DF4A885A1F04AA634AB }}

      - name: Run az commands
        run: |
          az account show
          az group list

      - name: Deploy to Azure Function App using CLI (Force Oryx Build)
        run: |
          az functionapp deployment source config-zip \
            --resource-group arraymorph \
            --name arraymorph \
            --src release.zip 
          