name: Build and deploy Python project to Azure Function App - arraymorph

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to function app
  PYTHON_VERSION: '3.11' # Python version used for deployment

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Ensure requirements.txt is up-to-date
      - name: Export dependencies
        run: pip freeze > requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: zip -r functionapp.zip ./* -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_51206E80E38A41708721B66B0F51BB28 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C3CEB54EDEFA4536ADF1E61CAEE49A85 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21C8ADD0FC794AC4968B8CE9B2CF4A7E }}

      - name: Deploy to Azure Function App using CLI
        run: |
          az functionapp deployment source config-zip \
            --resource-group arraymorph \
            --name arraymorph \
            --src functionapp.zip
